# .streamlit/secrets.toml

# 你的FastAPI后端服务地址
API_ENDPOINT = "http://127.0.0.1:8000/divination"

# 你的API密钥，请用你自己的密钥替换这里的文字
# 这个密钥是通过 python create_api_key.py --owner webui 生成的
API_KEY = "-DlYjQ5uuSGVa63rP10rtvlTn9mCmOsllJroY2gbWqk"